# Generated by Django 2.1.5 on 2019-03-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='video_link',
            field=models.TextField(blank=True),
        ),
    ]
