# Generated by Django 2.1.5 on 2019-05-16 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import puzzlehunt.models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0002_puzzle_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=puzzlehunt.models.Comments.posted_datetime_func)),
            ],
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='example',
        ),
        migrations.AddField(
            model_name='comments',
            name='puzzle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzlehunt.Puzzle'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
